project:
  type: website
  output-dir: docs

website:
  title: "💧 Water & Adolescent SA | SRCD 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: references.qmd
        text: References
      - href: poster.qmd
        text: Poster
    right:
      - icon: github
        href: https://github.com/ccani007

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-fold: true
    bibliography: references.bib
    csl: apa.csl
    citation-style: apa
    css: styles.css 